### ISSUE TITLE
Keyboard keys

### ISSUE THREAD

**Issue by aymanbagabas** [mariusrodi/linux-on-huawei-matebook-13#1]
Hey, I've been working on this [driver](https://github.com/aymanbagabas/Huawei-WMI) for a while to integrate these missing keys on huawei laptops. So far, it has been tested on
* Matebook x (2017)
* Matebook x pro (2018)

Would you be able to test it? I would be happy to help to fix this issue on this laptop.
Thank you

**Comment by mariusrodi** [comment]
Hey, thanks for the recommendation, nice work. I tried out your driver but couldn't get it to work.

I am currently using Manjaro Linux on Kernel 4.19.42-1 and followed your installation guide for Linux Kernel Versions < 5.
I will open an issue on your Repo with an error dump.

**Comment by mariusrodi** [comment]
So I've upgraded to Linux Kernel 5.1.5-050105-generic and installed your driver. All Media Control Keys are working except for the ones from F7 to F10.
I have tested it on Elementary OS. Before installing your driver but with Kernel 5.1.5-050105-generic all Media Control Keys worked except F8 and F10.

**Comment by aymanbagabas** [comment]
> So I've upgraded to Linux Kernel 5.1.5-050105-generic and installed your driver. All Media Control Keys are working except for the ones from F7 to F10.
> I have tested it on Elementary OS. Before installing your driver but with Kernel 5.1.5-050105-generic all Media Control Keys worked except F8 and F10.

The keyboard part hasn't changed from the version equipped with kernel and with the one on the repository. They should behave the same!

F7 needs remapping, see the readme.
F8 is mapped to Super+p and doesn't have any specialty key event. You can check that using something like `xev`. It's also the same in Windows
F9 should work on any modern desktop environment and it's mapped to XF86WLAN. You can use `acpi_listen` to see this event or `evtest`.
F10 is mapped to XF86Tools, which in GNOME launches the settings by default.
You can see all the mapped keys using `evtest`

If you're seeing different behavior from the one on the repo, please open up an issue. Thank you!
