### ISSUE TITLE
Headphone jack and more

### ISSUE THREAD

**Issue by nekr0z** [mariusrodi/linux-on-huawei-matebook-13#2]
I've started [this repository](https://github.com/nekr0z/linux-on-huawei-matebook-13-2019) about the same time you've started yours, but somehow mine happened to became a little more popular and received more input from different people, which helped to figure out solving keyboard issues, battery protection, headphone jack and more. Feel free to use and chip in!

**Comment by mariusrodi** [comment]
Thanks mate.
